version: '3.9'

services:
  
  server:
    
    build: 
    
      context: ./

      dockerfile: ./dockerfiles/server.dockerfile

    ports:
      
      - "3000:3000"

    volumes:
      
      - /app/node_modules
      
      - ./app:/app
  
  preview:
    
    build: 
    
      context: ./

      dockerfile: ./dockerfiles/server.dockerfile

    ports:
      
      - "3000:3000"

    volumes:
      
      - /app/node_modules


  npm:
    
    build: 
      
      context: ./
      
      dockerfile: ./dockerfiles/npm.dockerfile
  

    tty: true
    
    stdin_open: true
    
    volumes:
      
      - ./app:/app

  
  
  astro:
    
    build: 
      
      context: ./
      
      dockerfile: ./dockerfiles/astro.dockerfile
  
    tty: true
    
    stdin_open: true
    
    volumes:
           
      - ./app:/app

